# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/adams/Desktop/S4/Projet/ProjetS4/Code/AudioMX-Projet-S4/projet_vivado/projet_vivado.srcs/sources_1/bd/main_design/ip/main_design_axi_fifo_mm_s_1_0_1/main_design_axi_fifo_mm_s_1_0.xci
# IP: The module: 'main_design_axi_fifo_mm_s_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adams/Desktop/S4/Projet/ProjetS4/Code/AudioMX-Projet-S4/projet_vivado/projet_vivado.gen/sources_1/bd/main_design/ip/main_design_axi_fifo_mm_s_1_0_1/main_design_axi_fifo_mm_s_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_axi_fifo_mm_s_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/adams/Desktop/S4/Projet/ProjetS4/Code/AudioMX-Projet-S4/projet_vivado/projet_vivado.srcs/sources_1/bd/main_design/ip/main_design_axi_fifo_mm_s_1_0_1/main_design_axi_fifo_mm_s_1_0.xci
# IP: The module: 'main_design_axi_fifo_mm_s_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adams/Desktop/S4/Projet/ProjetS4/Code/AudioMX-Projet-S4/projet_vivado/projet_vivado.gen/sources_1/bd/main_design/ip/main_design_axi_fifo_mm_s_1_0_1/main_design_axi_fifo_mm_s_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_axi_fifo_mm_s_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
