# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gabma/Projet S4/labo1_final/labo1/projet_vivado/projet_vivado.srcs/sources_1/bd/main_design/ip/main_design_auto_pc_2/main_design_auto_pc_2.xci
# IP: The module: 'main_design_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gabma/Projet S4/labo1_final/labo1/projet_vivado/projet_vivado.gen/sources_1/bd/main_design/ip/main_design_auto_pc_2/main_design_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/gabma/Projet S4/labo1_final/labo1/projet_vivado/projet_vivado.srcs/sources_1/bd/main_design/ip/main_design_auto_pc_2/main_design_auto_pc_2.xci
# IP: The module: 'main_design_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gabma/Projet S4/labo1_final/labo1/projet_vivado/projet_vivado.gen/sources_1/bd/main_design/ip/main_design_auto_pc_2/main_design_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
