# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/adams/Desktop/S4/Projet/ProjetS4/Code/AudioMX-Projet-S4/env_vivado/vhdl/const/main_design_constr.xdc

# Block Designs: bd/main_design/main_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design || ORIG_REF_NAME==main_design} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_gpio_0_0/main_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_gpio_0_0 || ORIG_REF_NAME==main_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xbar_0/main_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xbar_0 || ORIG_REF_NAME==main_design_xbar_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_interconnect_0_0/main_design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_interconnect_0_0 || ORIG_REF_NAME==main_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_quad_spi_0_0/main_design_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_quad_spi_0_0 || ORIG_REF_NAME==main_design_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_uartlite_0_0/main_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_uartlite_0_0 || ORIG_REF_NAME==main_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_clk_wiz_1_0/main_design_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_clk_wiz_1_0 || ORIG_REF_NAME==main_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_mdm_0_0/main_design_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_mdm_0_0 || ORIG_REF_NAME==main_design_mdm_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_0/main_design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_0 || ORIG_REF_NAME==main_design_microblaze_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_axi_intc_0/main_design_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==main_design_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xbar_1/main_design_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xbar_1 || ORIG_REF_NAME==main_design_xbar_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_axi_periph_0/main_design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==main_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_xlconcat_0/main_design_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_xlconcat_0 || ORIG_REF_NAME==main_design_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_processing_system7_0_0/main_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_processing_system7_0_0 || ORIG_REF_NAME==main_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_rst_clk_wiz_1_100M_0/main_design_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==main_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconcat_0_0/main_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlconcat_0_0 || ORIG_REF_NAME==main_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_0_0/main_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlconstant_0_0 || ORIG_REF_NAME==main_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_auto_us_0/main_design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_auto_us_0 || ORIG_REF_NAME==main_design_auto_us_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_auto_us_1/main_design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_auto_us_1 || ORIG_REF_NAME==main_design_auto_us_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_auto_pc_0/main_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_auto_pc_0 || ORIG_REF_NAME==main_design_auto_pc_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_auto_pc_1/main_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_auto_pc_1 || ORIG_REF_NAME==main_design_auto_pc_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_auto_pc_2/main_design_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_auto_pc_2 || ORIG_REF_NAME==main_design_auto_pc_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xfft_0_0_1/main_design_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xfft_0_0 || ORIG_REF_NAME==main_design_xfft_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_fifo_mm_s_0_0_1/main_design_axi_fifo_mm_s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==main_design_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_fifo_mm_s_1_0_1/main_design_axi_fifo_mm_s_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_fifo_mm_s_1_0 || ORIG_REF_NAME==main_design_axi_fifo_mm_s_1_0} -quiet] -quiet

# XDC: c:/Users/adams/Desktop/S4/Projet/ProjetS4/Code/AudioMX-Projet-S4/projet_vivado/projet_vivado.gen/sources_1/bd/main_design/main_design_ooc.xdc
